### ISSUE TITLE
Application crash after I rename

### ISSUE THREAD

**Issue by nqmgaming** [aarash709/VoiceRecorder#119]
Rename work but it's crash

Log:    E  FATAL EXCEPTION: main (Ask Gemini)
                                                                                                    Process: com.experiment.voicerecorder, PID: 7582
                                                                                                    java.lang.IllegalArgumentException: 
/storage/emulated/0/Android/data/com.experiment.voicerecorder/files/11.34, 29 May does not exist
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:255)
                                                                                                    	at com.core.common.TimeUtilsKt.mediaDurationInMillis(TimeUtils.kt:36)
                                                                                                    	at com.core.common.Storage$getVoices$2.invokeSuspend(Storage.kt:26)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:111)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:99)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@655f9b7, Dispatchers.Main.immediate]

**Comment by nqmgaming** [comment]
fixed
